backspaceCompare("ab#c", "ad#c"); // true
backspaceCompare("ab##", "c#d#"); // true
backspaceCompare("a##c", "#a#c"); // true
backspaceCompare("a#c", "b"); // false
backspaceCompare("ab#z", "az#z"); // true
backspaceCompare("abc#d", "acc#c"); // false
backspaceCompare("x#y#z#", "a#"); // true
backspaceCompare("a###b", "b"); // true
backspaceCompare("Ab#z", "ab#z"); // false
