isValid("()"); // true
isValid("()[]{}"); // true
isValid("(]"); // false
isValid("([)]"); // false
isValid("{[]}"); // true
isValid("{([])}"); // true
isValid("{([]"); // false
isValid("{[(])}"); // false
isValid("{[]()}"); // true
